### ISSUE TITLE
Changing printer properties

### ISSUE THREAD

**Issue by szilardx** [MerrionComputing/PrintQueueWatch#8]
First, I have to say, that I appreciate this library very much. It helped me a lot solving print management issues.

My question is: Does changing printer properties through PrinterQueueWatch library supposed to work on Windows 10?

For example I tried changing the KeepPrintedDocuments property, but it has no effect - the setting is not changed in the Printer Properties - Advanced tab. 

Example code:
(The printer exists on Windows, the library works otherwise ie.: printer events are fired. Code running in admin mode)
```
            foreach (var printQueue in new PrinterQueueWatch.PrintServer().Printers)
            {
                 if(printQueue.PrinterName == "Xerox AltaLink C8045 PCL6")
                {
                   // changing these properties has no effect
                    printQueue.KeepPrintedDocuments = true;
                    printQueue.EnableAdvancedPrintingFeatures = false;
                    printQueue.HoldMismatchedDocuments = true;
                }
            }
```

**Comment by szilardx** [comment]
I realized, that my problem was that this line only queries printers with a read access right:
`PrinterQueueWatch.PrintServer().Printers`

When queried with the proper access right, the property is changed:
`new PrinterInformation("Printer Name", PrinterQueueWatch.SpoolerApiConstantEnumerations.PrinterAccessRights.PRINTER_ALL_ACCESS, true);`

**Comment by MerrionComputing** [comment]
Enumerating the printers fails if the user hasn't the requested access so I enumerate with the lowest access rights.
